version: "3.9"

services:
  php-apache:
    image: djedjethai/mediter:0.0.1
      # image: djedjethai/mediter:1.0.2 # production image
    environment:
      MYSQL_USER: /run/secrets/mysql-user
      MYSQL_PASSWORD: /run/secrets/mysql-password
      API_KEY: /run/secrets/api-key
    secrets:
    - mysql-user
    - mysql-password
    - api-key
    ports:
    - "80:80"  
    - "443:443"  
    volumes:
    - ./sites-enabled/:/etc/apache2/sites-enabled/
    - ./data/logs:/var/www/html/Web/errLogger
    - ./data/pictures:/var/www/html/Web/pictures
    networks:
    - mynet

  mysql:
    image: mysql:5.6.40
    environment:
      MYSQL_USER_FILE: /run/secrets/mysql-user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-password
      MYSQL_DATABASE_FILE: /run/secrets/mysql-database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
    secrets:
    - mysql-user
    - mysql-password
    - mysql-database
    - mysql-root-password
    ports:
    - "3306:3306"
    networks:
    - mynet
    volumes:
    - /home/jerome/Documents/code/phpMediterpourgrandir/data/mysql:/var/lib/mysql
      
networks:
  mynet:

secrets:
  mysql-user:
    external: true
  mysql-password:
    external: true
  mysql-database:
    external: true
  mysql-root-password:
    external: true
  api-key:
    external: true
