version: "3.9"

services:
  php-apache:
    image: djedjethai/mediter
    ports:
    - "80:80"  
    - "443:443"  
    volumes:
    # for dev
    #- ./apache-php/MediterPourGrandir/:/var/www/html/  
    - ./curl/:/opt/lampp/share/curl/
    - ./sites-enabled/:/etc/apache2/sites-enabled/
    - ./certificate/:/certificate/
    networks:
    - mynet
  
  mysql:
    image: mysql:5.6.40
    environment:
      MYSQL_USER: lasolution
      MYSQL_PASSWORD: cestdedevelopperledharma
      MYSQL_DATABASE: monsupersite 
      MYSQL_ROOT_PASSWORD: thisisabigsecretyouwontguessit
    ports:
    - "3306:3306"
    networks:
    - mynet
      #volumes:
      #- mysql-db:/var/lib/mysql
      
networks:
  mynet:

          #volumes: 
          # mysql-db:


